### ISSUE TITLE
[Feature] support generating `dev`/`scm` rockspecs

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/luarocks-tag-release#369]
If no version is set, or it is set to `dev` or `scm`, and there is no semver tag, generate a `scm` rockspec.

**Comment by rktjmp** [comment]
Per the readme

> version (optional)
>
> The package version to release to LuaRocks (without the rockspec revision). By default, this workflow will use the git tag to determine the LuaRocks package version. If you do not have a workflow that releases based on tags, you can manually set the version input.
> 
> Setting this input to either null, "scm" or "dev" will result in a scm release, where the generated rockspec's source URL is the repository's URL.

I think this section should have a note saying you *must* include `version: null | 'scm' | 'dev'` as dropping the key entirely https://github.com/rktjmp/playtime.nvim/commit/9950b19697a48e9c22993e1271dd21612649b193 gave me a `main-1` version, instead of `scm-1` version. https://github.com/rktjmp/playtime.nvim/commit/b9b9253f562b81d0b365cc644d80f2f97ac23dda (I did not test `null` but that might also generate `main-1`, not sure if a missing key is handled differently to an existing key set to null). Or the behaviour might need to be fixed?

I dont have a lot of experience with luarocks, I assume `main-1` (or `master-1` depending on the main branch name) and `scm-1` are functionally the same, as they're both tagged as "dev" releases, but I think `scm-1` is more standard.

**Comment by mrcjkb** [comment]
@rktjmp thanks for the feedback. 
I've added a clarification: https://github.com/nvim-neorocks/luarocks-tag-release/commit/9696a5c8f9578227b0a9c6a5c53b37a5b7a766d5
