### ISSUE TITLE
Exclude directory

### ISSUE THREAD

**Issue by AMD-NICK** [nvim-neorocks/luarocks-tag-release#48]
Creating a luarocks file for me (and I'm sure not just for me) is a task that takes away the desire to load lua modules into luarocks. Honestly, I still don't fully understand how it works and constantly think about how to organize it conveniently. But it seems that there are no simple solutions.

I am not a neovim user, but I came across this repository and tried to apply it to one of my modules: https://github.com/TRIGONIM/lua-requests-async

Overall, the action works great, but it's pretty "rough". For example, in the repository, I have a folder called examples with a set of lua files, but it becomes part of the module when it is installed, and I don't know how to properly add it to the list of ignored files.

Actually, this is the only problem I have encountered so far, but it would be great if you assumed the possibility of applying your Github action to a wide range of modules.

**Comment by mrcjkb** [comment]
Hi, thanks for the feedback :smile: 

I do intend to keep this workflow compatible with non-neovim packages. There may be some limitations, like the fact that it currently assumes Lua 5.1, and only uses Lua 5.1 as an interpreter.
The first limitation can be solved [by specifying a rockspec template](https://github.com/nvim-neorocks/luarocks-tag-release#template).  The second one may be solved if I add the ability to specify the interpreter - I've been playing around with the idea in #47.

Something you may want to consider when publishing non-neovim packages is to explicitly set the [`copy_directories` input](https://github.com/nvim-neorocks/luarocks-tag-release#copy_directories), without the `{{ neovim.plugin.dirs }}` expression. Otherwise the action will look for common neovim plugin directories, which you may not want to copy in a regular lua package.

`examples` is not one of those directories, though.
The reason i think luarocks may be copying your entire repository is that you don't have your scripts in a `lua` subdirectory. They are in the root of your repository. So luarocks sees the entire repo as the library. 

If you move the scripts to a `lua` subdirectory, that should fix it.

**Comment by AMD-NICK** [comment]
It works, thank you.
